#! /bin/bash

cp .bash_profile ~

source ~/.bash_profile

./scripts/bvimrc


if [[ -z which brew ]]; then
  if [[  -z `which tree` ]]; then
      brew install tree
  fi

  #install atom
  #   nuclide
  #   git log
  #   atom-ternjs
  #   language-babel (or react?) https://orktes.github.io/atom-react/#syntax-highlighting
  #   highlight selected?
  #   linter-eslint (ignore linter dependency)
  #   js-refactor
  #   prettier-atom
  #   mocha-test-runner
fi
