#! /bin/bash
# TODO: fix this

lines=$(ls -FGlAhp $@ | sed 1d )

curdir=$(pwd)

output=""
#echo "$lines" | while IFS='' read -r line
while read -r line
do
    dir=${line##* }
    if [ -d $dir ]; then
        cd "$dir"
        if [ -d .git ]; then
            status=$(gitstatus)
            output=$output"
${line% *} $(tput setaf 4)${dir%?}$(tput sgr0)/ $status"
        else
            output=$output"
${line% *} $(tput setaf 4)${dir%?}$(tput sgr0)/"
        fi
        cd "$curdir"
    else
        output=$output"
$line"
    fi
done < <(echo "$lines")

echo "$output"


