#! /bin/bash
lines=$(ls -FGlAhp | sed 1d )

curdir=$(pwd)

output=""
#echo "$lines" | while IFS='' read -r line
while read -r line
do
    dir=${line##* }
    if [ -d $dir ]; then
        cd "$dir"
        status=$(gitstatus)
        output=$output"
$line $status"
        cd "$curdir"
    fi
done < <(echo "$lines")

echo "$output"


